version: '3.1'

services:
  db1:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: g4user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: dbmovie
    ports:
      - "3306:3306"    

  db2:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: g4user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbmovie
    ports:
      - "5432:5432"      
